### ISSUE TITLE
No error notification when syncing projects and "lein" can't be found

### ISSUE THREAD

**Issue by alshain** [gregsh/Clojure-Kit#25]
It would be nice if a small Tooltip could be shown if project synchronization fails.

I just get this exception in idea.log which makes it clear what I need to do, but I was wondering why nothing seemed to happen for a while.

```
2018-11-27 11:07:20,291 [ 690536]  ERROR - intellij.openapi.progress.Task - Cannot run program "lein" (in directory "C:\Entwicklungstools\workspace\VisualReview"): CreateProcess error=2, Das System kann die angegebene Datei nicht finden 
com.intellij.execution.process.ProcessNotCreatedException: Cannot run program "lein" (in directory "C:\Entwicklungstools\workspace\VisualReview"): CreateProcess error=2, Das System kann die angegebene Datei nicht finden
	at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:416)
	at com.intellij.execution.process.OSProcessHandler.startProcess(OSProcessHandler.java:51)
	at com.intellij.execution.process.OSProcessHandler.<init>(OSProcessHandler.java:44)
	at org.intellij.clojure.tools.Tools_depsKt.collectDeps(tools-deps.kt:181)
	at org.intellij.clojure.tools.Tools_depsKt.access$collectDeps(tools-deps.kt:1)
	at org.intellij.clojure.tools.ClojureProjectDeps$resolveDepsInBackground$1.run(tools-deps.kt:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:727)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:582)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:87)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:403)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:314)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: Cannot run program "lein" (in directory "C:\Entwicklungstools\workspace\VisualReview"): CreateProcess error=2, Das System kann die angegebene Datei nicht finden
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at com.intellij.execution.configurations.GeneralCommandLine.startProcess(GeneralCommandLine.java:444)
	at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:412)
	... 18 more
Caused by: java.io.IOException: CreateProcess error=2, Das System kann die angegebene Datei nicht finden
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(ProcessImpl.java:386)
	at java.lang.ProcessImpl.start(ProcessImpl.java:137)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 20 more
```

**Comment by jcjolley** [comment]
What was the fix to this?  I am getting the same error but can't seem to resolve it.
